package com.goalmoney.personal;
import android.content.*;import org.json.*;import java.util.*;
public class DataStore {
 public long spending=15000000L; public final List<Models.Goal> goals=new ArrayList<>(); public final List<Models.Tx> txs=new ArrayList<>(); private static final String P="gm_v2";
 public DataStore(Context c){String s=c.getSharedPreferences(P,0).getString("data","");if(s.isEmpty())s=c.getSharedPreferences("gm",0).getString("data","");if(s.isEmpty()){goals.add(new Models.Goal(System.currentTimeMillis(),"Mua điện thoại","phone",25000000,6000000,""));goals.add(new Models.Goal(System.currentTimeMillis()+1,"Trả nợ","debt",12000000,3500000,""));}else load(s);}
 public long goalsTotal(){long x=0;for(Models.Goal g:goals)x+=g.current;return x;} public long total(){return spending+goalsTotal();} public Models.Goal goal(long id){for(Models.Goal g:goals)if(g.id==id)return g;return null;}
 public String json(){try{JSONObject o=new JSONObject();o.put("version",2);o.put("spending",spending);JSONArray a=new JSONArray();for(Models.Goal g:goals){JSONObject x=new JSONObject();x.put("id",g.id);x.put("name",g.name);x.put("type",g.type);x.put("target",g.target);x.put("current",g.current);x.put("deadline",g.deadline);a.put(x);}o.put("goals",a);JSONArray b=new JSONArray();for(Models.Tx t:txs){JSONObject x=new JSONObject();x.put("id",t.id);x.put("type",t.type);x.put("title",t.title);x.put("from",t.from);x.put("to",t.to);x.put("amount",t.amount);x.put("goalId",t.goalId);x.put("date",t.date);x.put("time",t.time);x.put("note",t.note);x.put("category",t.category);b.put(x);}o.put("txs",b);return o.toString(2);}catch(Exception e){return "{}";}}
 public boolean load(String s){try{JSONObject o=new JSONObject(s);if(!o.has("spending")||!o.has("goals")||!o.has("txs"))return false;spending=o.optLong("spending");goals.clear();JSONArray a=o.optJSONArray("goals");if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);goals.add(new Models.Goal(x.getLong("id"),x.getString("name"),x.optString("type","other"),x.getLong("target"),x.getLong("current"),x.optString("deadline","")));}txs.clear();JSONArray b=o.optJSONArray("txs");if(b!=null)for(int i=0;i<b.length();i++){JSONObject x=b.getJSONObject(i);txs.add(new Models.Tx(x.getLong("id"),x.getString("type"),x.getString("title"),x.getString("from"),x.getString("to"),x.getLong("amount"),x.optLong("goalId"),x.getString("date"),x.getString("time"),x.optString("note"),x.optString("category","Khác")));}return true;}catch(Exception ignored){return false;}}
 public String csv(){StringBuilder b=new StringBuilder("\uFEFFNgày,Giờ,Loại,Danh mục,Nguồn,Đích,Số tiền,Ghi chú\n");for(Models.Tx t:txs)b.append(q(t.date)).append(',').append(q(t.time)).append(',').append(q(t.type)).append(',').append(q(t.category)).append(',').append(q(t.from)).append(',').append(q(t.to)).append(',').append(t.amount).append(',').append(q(t.note)).append('\n');return b.toString();}
 private String q(String s){return "\""+(s==null?"":s.replace("\"","\"\""))+"\"";}
 public void save(Context c){c.getSharedPreferences(P,0).edit().putString("data",json()).apply();c.getSharedPreferences("goal_widget",0).edit().putLong("total",total()).putLong("spending",spending).putLong("goals",goalsTotal()).putInt("count",goals.size()).apply();GoalMoneyWidget.refreshAll(c);}
}
