package com.goalmoney.personal;
import android.content.*;import android.graphics.*;import android.view.*;import java.text.*;import java.util.*;
public class SimpleChartView extends View {
 private List<Models.Tx> data=new ArrayList<>(); private String range="month"; private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
 public SimpleChartView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);} public void setData(List<Models.Tx> d){data=d;invalidate();} public void setRange(String r){range=r;invalidate();}
 static class Row{String key,label;long in,out;Row(String k,String l){key=k;label=l;}}
 private List<Row> rows(){List<Row> r=new ArrayList<>();Calendar now=Calendar.getInstance();if("day".equals(range)){for(int i=6;i>=0;i--){Calendar c=(Calendar)now.clone();c.add(Calendar.DAY_OF_YEAR,-i);r.add(new Row(new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.getTime()),new SimpleDateFormat("dd/MM",Locale.US).format(c.getTime())));}}else if("year".equals(range)){for(int i=4;i>=0;i--){int y=now.get(Calendar.YEAR)-i;r.add(new Row(String.valueOf(y),String.valueOf(y)));}}else{for(int i=5;i>=0;i--){Calendar c=(Calendar)now.clone();c.add(Calendar.MONTH,-i);r.add(new Row(new SimpleDateFormat("yyyy-MM",Locale.US).format(c.getTime()),"T"+(c.get(Calendar.MONTH)+1)));}}for(Models.Tx t:data)for(Row x:r)if(t.date.startsWith(x.key)){if("income".equals(t.type))x.in+=t.amount;if("expense".equals(t.type))x.out+=t.amount;}return r;}
 @Override protected void onDraw(Canvas c){super.onDraw(c);List<Row> rs=rows();int w=getWidth(),h=getHeight();long max=1;for(Row x:rs)max=Math.max(max,Math.max(x.in,x.out));float left=45,right=w-25,top=32,bottom=h-55,usable=bottom-top;p.setStrokeWidth(2);p.setColor(Color.rgb(232,237,245));for(int i=0;i<5;i++){float y=top+usable*i/4;c.drawLine(left,y,right,y,p);}float step=(right-left)/Math.max(1,rs.size()-1);drawLine(c,rs,true,Color.rgb(19,160,111),max,left,top,bottom,step);drawLine(c,rs,false,Color.rgb(228,72,95),max,left,top,bottom,step);p.setColor(Color.rgb(123,135,157));p.setTextSize(20);p.setTextAlign(Paint.Align.CENTER);for(int i=0;i<rs.size();i++)c.drawText(rs.get(i).label,left+i*step,h-18,p);}
 private void drawLine(Canvas c,List<Row> rs,boolean income,int color,long max,float left,float top,float bottom,float step){Path path=new Path();p.setColor(color);p.setStrokeWidth(6);p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<rs.size();i++){long v=income?rs.get(i).in:rs.get(i).out;float x=left+i*step,y=bottom-v*(bottom-top)/max;if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,p);p.setStyle(Paint.Style.FILL);for(int i=0;i<rs.size();i++){long v=income?rs.get(i).in:rs.get(i).out;float x=left+i*step,y=bottom-v*(bottom-top)/max;c.drawCircle(x,y,7,p);}}
}
